name: PHP Unit
on: [ push, pull_request ]

defaults:
  run:
    working-directory: ./laravel

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extension-csv: mbstring, xdebug
      - name: Add Plugin
        run: sudo apt install -y php7.4-xml
      - name: Check PHP Version
        run: php -v
      - name: Check Composer Version
        run: composer -V
      - name: Check PHP Extensions
        run: php -m
      - name: Change Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Install Libraries
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Set env
        run: cp .env.example .env
      - name: Run migration
        run: php artisan migrate --database=mysql_testing --force
      - name: Run PHP Unit
        run:  php artisan key:generate && composer run test
